### ISSUE TITLE
DNS resolution can cause monitoring to go OOM

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/geoserver#125]
A DNS reverse lookup is always performed as a post-task in monitoring, in a background thread.
If the DNS does not respond the thread queue can grow indefinitely and cause OOM.

Since the DNS reverse lookup operation in Java has no timeout settings, add a way to disable the reverse lookups instead. @simboss suggested to do it by default, however, that would break backwards compatibility, so not sure...

**Comment by nmco** [comment]
@imranrajjad can you propose a plan for this and estimate?

**Comment by imranrajjad** [comment]
@nmco 

so the things needs to be done as proposed in the document

-Make DNS lookup configurable, that will require a new configurable option in properties file, that can define an ignore processor list.
-Create a cache, which will store information repeated in requests e.g IP, Location and other fields (perhaps the list is long). The  cache will need some sort of configuration also. As in life time of cache entries. 

Initial estimate is 4 days

**Comment by nmco** [comment]
@imranrajjad could you detail more your plan? Your plan description shoudl answer at least the questions bellow:

Regarding the configuration:

> -Make DNS lookup configurable, that will require a new configurable option in properties file, that can define an ignore processor list.

What do you mean by configurable? Deactivate or activate?
Which properties file? 
What do you mean by _can define an ignore processor list_?

Regarding the cache:

> -Create a cache, which will store information repeated in requests e.g IP, Location and other fields (perhaps the list is long). The cache will need some sort of configuration also. As in life time of cache . entries. The cache can comprise of multiple values, dns,location,etc

Where and when will the cache be used? What's is propose? What data will it contain?
How will the cache be configured?
How do you intend to implement the cache? Which technology, you shoudl check what's currently used in GeoServer?

**Comment by imranrajjad** [comment]
### Detailed Implementation Plan

@nmco The issue revolves around asynchronous DNS lookup calls that amass a lot of objects in memory and eventually resulting in an OOO. As suggested by the investigation document, the `monitor` extension needs to features

#### 1. Ability to Enable/Disable DNS Lookup
We should be able to disabled `ReverseDNSPostProcessor` (or any other processor that might derade the plugin due to external factors e.g a slow DNS server etc). To do this following set of changes will be required.

1. Add a new method `getProcessName()` to [RequestPostProcessor.java](https://github.com/geoserver/geoserver/blob/master/src/extension/monitor/core/src/main/java/org/geoserver/monitor/RequestPostProcessor.java). This method should return unique name of each implementation of **RequestPostProcessor** interface.
2. Add new option in `monitor.properties` which can take list of post processors to ignore (e.g ignoreList=reverseDNSLoopUp). Through the [MonitorConfig.java](https://github.com/geoserver/geoserver/blob/master/src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorConfig.java) bean, this property will be available in [Monitor.java](https://github.com/geoserver/geoserver/blob/master/src/extension/monitor/core/src/main/java/org/geoserver/monitor/Monitor.java) an ArrayList<String>.
3. Then we can use the arraylist inside Monitor config at [MonitorFilter.PostProcessTask.run](https://github.com/geoserver/geoserver/blob/master/src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorFilter.java#L294) to decide if a certain request processor needs to be skipped.

#### 2. Caching DNS lookups
As per my understanding, the DNS is looked up for each request, and a slow DNS lookup can leave objects hanging in memory. As suggested in initial investigation report document, it would help to cache the results of DNS look ups. The cache will created inside [ReverseDNSPostProcessor.java](https://github.com/geoserver/geoserver/blob/master/src/extension/monitor/core/src/main/java/org/geoserver/monitor/ReverseDNSPostProcessor.java).  The cache entries must have an expiration. To do this some third party libraries are available such as:

1. [Google Gauva Cache Builder](https://github.com/google/guava/wiki/CachesExplained)
2. [EHCACHE](https://www.ehcache.org/documentation/3.1/expiry.html)

These APIs might come with their baggage of configuration which will end up in `monitor.properties`, an alternate is to expire the cache on need bases and without any background polling thread. To do so we can simply insert the DNS results against IPs inside a concurrent Hashmap with a wrapper keeping note of the date/time of entry.

So say we want to remember the DNS lookup for any IP for 1 hour _(3600 sec)_. The ReverseDNSPostProcessor will lookup for the IP in cache before making the reverse DNS request, if it does not find any entry or the existing entry is more than 1 hour old, the processor will make a reverse DNS lookup request and update cache, otherwise it will take cache entry and skip making an unnecessary reverse DNS lookup.
To configure the cache (enable/disable and timeout), `monitor.properties` will require to store these configurations which can look something like

```
reverseDNS.cache=true
reverseDNS.timeout_seconds=3600

```

**Comment by imranrajjad** [comment]
@aaime can you please verify and comment on my plan to get around this issue.

**Comment by aaime** [comment]
I had a look at the code, the reverse DNS lookup is already caching the recent IPs using a soft cache with 100 hard references (the others will be soft references), so it seems a new cache is not needed after all (please update your estimates accordingly). The original "timeout" considerations were based on the DNS lookup operation itself, which does not seem to accept a network timeout. Adding a timeout for the cache is a nice to have, but not a requirement, please estimate it separately, @simboss will tell us if it's needed.

The proposed configuration of post-processors looks good, I'd just call its configuration property ``ignorePostProcessors``.

**Comment by imranrajjad** [comment]
@aaime thanks for the feedback

updated estimates:
Cache timeout : 1 day
Ignoring post processors: 1 day

**Comment by imranrajjad** [comment]
@aaime 

PR : https://github.com/geoserver/geoserver/pull/3943

contains implementation of ignoring post processors

**Comment by nmco** [comment]
What's missing here @imranrajjad, only the final review from @aaime ?

**Comment by imranrajjad** [comment]
@nmco yes,
