### ISSUE TITLE
Introduce gridsets with 512x512 tile size for common CRSs

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geoserver#156]
The rationale is simple, we need to reduce the requests for tiles where possible, hence we often use 512x512 tile size.
Why we don't make this available by default in GeoServer and be done with it?

Discussion open.

**Comment by nmco** [comment]
I don't see any major issue in introducing for all the default grid-sets we already provide a 512x512 version, we could name the tile matrix sets using something like ``EPSG:4326_512x512``, I'm not aware of an already defined pattern for this.

**Comment by aaime** [comment]
GWC gridsets are very outdated and have not been matching the well known gridset names for a while, and have some naming conventions that make up for emabarassing URLs (e.g., CRS name repeated in zoom level names). 
If we go about changing the GWC default gridsets, I suggest also considering aligning names with the OGC standard: http://docs.opengeospatial.org/is/17-083r2/17-083r2.html

**Comment by nmco** [comment]
Thinking out loud, if we know that a GeoServer instance will only be used by clients that already expect 512x512 to be provided, we could have a checkbox that would make the default ones be actually converted and published using 512x512 tiles. Not a very standard thing but would make things more practical.

**Comment by aaime** [comment]
Checked:

- Just adding a couple of 512px tiles based gridsets is easy, say 2-4 hours
- Adding the gridsets from the OGC standard (they are all 256px based mind) can take another 8 hours. I'd recommend to go and do both, so that we can do the 512px gridsets based on the new standard names, e.g., WorldCRS84Quad512, rather than EPSG:4326_512, as having ":" in the path of a OGC API Tile looks like a sore eye.
- If we do both the list will become a bit long, so the GUI in GeoServer for selecting the gridsets should be updated to allow reducing the dropdown list as one types. This would add another couple of hours.

**Comment by nmco** [comment]
So the full estimate is 16 hours @aaime? Is this something we should do as an internal task  @simboss ?

**Comment by simboss** [comment]
yes.

This is to match MapStore tiling which now by default can do 256 or 512, so let's test that as well.

**Comment by aaime** [comment]
Asked on the PSC meeting yesterday, no objection. PR is building: https://github.com/GeoWebCache/geowebcache/pull/934
