### ISSUE TITLE
Create new community module for GSR

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geoserver#158]
[GSR](https://github.com/geosolutions-it/gsr) is a plugin for GeoServer that helps it to mimic ESRI REST Services ( a subset of them).  The right branch is [this one](https://github.com/geosolutions-it/gsr/tree/2.16.x).

Given the new rules for contributing code back to GeoServer delinated in [GSIP-186](https://github.com/geoserver/geoserver/wiki/GSIP-186) we can now move this module back inside GeoServer as a community module, hence let's start this process engaging the developers mailing list first.

I have assigned this task to @taba90 but @aaime and @nmco should help with the procedure given their experience.

**Comment by simboss** [comment]
@aaime notice that [there is a PR](https://github.com/geosolutions-it/gsr/pull/2) pending from 2019.

**Comment by nmco** [comment]
@taba90 (answering here so everyone can follow), so:
- Why do we need GSIP-186? Because it looks like the module was initially developed by [Jeffrey Smith Pacific Disaster Center](https://github.com/jsmithmap), GSIP-186 allows us to contribute it to GeoServer as community module but we need to [respect all the conditions](https://github.com/geoserver/geoserver/wiki/GSIP-186#proposal). 
- Although community modules have no releases, we need it on 2.17.x branch so we can notify the client that this community module is available in 2.17.0.

**Comment by nmco** [comment]
The time spend on this is to log as internal GeoServer time.

**Comment by taba90** [comment]
Here the pull request https://github.com/geoserver/geoserver/pull/4137. History from geosolutions repo has been preserver

**Comment by simboss** [comment]
hi @taba90 abd @nmco ideally this should also be backported to 2.16 and 2.17 (not sure the status there).

Talk to @aaime about feasibility...

**Comment by simboss** [comment]
hello @taba90 ?

My comment has been sitting with no response for 1W now...

**Comment by nmco** [comment]
I don't see any blocker in back-porting this community module to 2.17.x and 2.16.x, its a community module and this is a module that comes from 2.16.x., @aaime any objection?

That say @taba90 there is a [review](https://github.com/geoserver/geoserver/pull/4137) and mail from Jody that has been siting around for one week, so lets follow up on that review NOW. Looks like applying Jody requested changes shoudl not take long, **if you need more than a couple hours please ping me.**

In terms of next steps:
1. Once you have applied Jody requested changes, update the mail thread ASAP.
2. Since we didn't request for the backport right away (please do it next time) its better to start a new thread for that, please do it right away after 1.
3. Prepare the back-ports PRs.

Question @taba90, where you able to actually manually test this? Or are we trusting the integration tests only?

**Comment by taba90** [comment]
I've applied Jody's feedback, but I got difficulties with one feedback that is use the resource provided by jody in the documetation example. I've replied it and waiting for his feedback. I've also manually tested it from the geoserver interface provided by the module when build with geoserver with gsr profile.

**Comment by nmco** [comment]
Pull request merged:

**Comment by taba90** [comment]
Jody pointed to a problem in the devel-list with gsr documentation: gsr is not showing up in the community module index.html on geoserver site. However build documentation on updated master in my local environment did not lead to any problem
![Cattura](https://user-images.githubusercontent.com/46672505/79425001-5635bf00-7fc1-11ea-8ccc-d821cd0c3ee3.PNG)
Could be this due the fact that community index.rft didn't get rebuilt after the pr got merged?

**Comment by aaime** [comment]
@taba90 that seems to be the case. Please point Jody at https://github.com/geoserver/geoserver/blob/master/doc/en/user/source/community/index.rst to show it's likely a build/doc server issue.

**Comment by aaime** [comment]
Btw, I see it now in the docs: https://docs.geoserver.org/latest/en/user/community/index.html#community

**Comment by taba90** [comment]
thx @aaime, answering jody.

**Comment by jsmithmap** [comment]
@aaime Do you think it will be possible to merge the [pull request I submitted](https://github.com/geosolutions-it/gsr/pull/2) into the next release?  There are 2 fairly minor changes I needed to make it work with my client's existing data viewer.

**Comment by nmco** [comment]
@taba90 where are we this:

> @taba90 can you start the discussion request permission to backport this community module to 2.17.x? Since its a community module their should be no problem.

?

**Comment by nmco** [comment]
Hi @jsmithmap (I'm not aware of the full context of this project so what I'm about to suggests may not apply) but I would suggest that you perform your PR directly against [GeoServer GSR community module](https://github.com/geoserver/geoserver/tree/master/src/community/gsr ) :smile:.

@aaime since GSR has been contributed to GeoServer with the full history I guess we can deprecate https://github.com/geosolutions-it/gsr?

**Comment by taba90** [comment]
[2.17.x backport](https://github.com/geoserver/geoserver/pull/4194)

**Comment by jsmithmap** [comment]
@taba90 - Since it looks like the GSR module had some pending changes to be merged based on the link you provided, I went ahead and submitted a Pull request to the branch "backport-9564-to-2.17.x" in your fork with my changes.  If I should instead create the Pull Request against the main GeoServer repo just let me know.  Thanks everyone for the help.

**Comment by taba90** [comment]
thanks for your pull request @jsmithmap . I've made two from that one, against the master branch on Geoserver:
https://github.com/geoserver/geoserver/pull/4222
https://github.com/geoserver/geoserver/pull/4223
after they have been merged on master, I'll backport them to 2.17.x

**Comment by jsmithmap** [comment]
@taba90 Thank you for helping with this!
