### ISSUE TITLE
Implement an endpoint which returns the SLD Styler methods

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geoserver#199]
I suggest to add a REST API endpoint that will return the list of the SLD Service implemented methods.
This will give a client the option to enable / disable functionalities on the base of the service capabilities (e.g. standar deviation classification).

please @taba90 and @allyoucanmap coordinate on the response structure

**Comment by taba90** [comment]
@giohappy 
I've produce the feature and included it in the war provided to Stefano for testing according to our conversation.

 It was a quick thing but would need some more work in order to produce a pull request because the way some points of the code have been implemented are posing some problem to a quick full implementation of the endpoint (regarding the html output format). 

Let me know if I should go on with the pull request. I spent on this 1,5 hours and I would need 2-3 hours more.

**Comment by giohappy** [comment]
@taba90 what do you mean with html output format?

**Comment by taba90** [comment]
@giohappy nevermind, it was a false problem. The functionality has been merged on master, and a backport pr has been produced. Details on the jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9709

**Comment by taba90** [comment]
merged on master and on 2.17.x
