### ISSUE TITLE
SQL views are not saved if the layer is not saved too

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geoserver#229]
The Save button at the bottom of the *Edit SQL view* page when modifying a SQL View in GeoServer is expected to be enough to write and flush the configuration changes, at least from a user standpoint.
However this is not true, the layer must also be saved using the save button at the bottom of the main *Edit Layer* page, otherwise the changes to the SQL View are not applied.

From a user standpoint we shall strive to to avoide the need for multiple clicks, but above all to exit and silently not saving changes now we have both.

**Comment by simboss** [comment]
@aaime what do you suggest?

**Comment by aaime** [comment]
Are we talking about the issue of the other day, where the sql view was modified, but the feature type reported in the page was wrong? In that case, we need to debug the page code, I don't have an answer to your question, but it should be fixed.

If instead you're thinking that a sql view definition should really be applied so that all requests react to it right away (outside of the page), then no, it should not be done. The sql view definition is part of the FeatureTypeInfo, which at that point is potentially dirty for some other change in the page. The GUI should be update so that it does not say "save" instead, but something else (back to layer page?). A change of this behavior would also confuse people.

**Comment by simboss** [comment]
We are talking about what I showed the other day but I think you are remembering wrong.

The issue here is that you need to save twice and the user will mistakenly thinking after the first save that the work is done ( I was mistaken, Giovanni was and so was the client so ...).

From what you say I think we need to make it more clear for the end user that we need to save twice before having the behavior applied, because with the current behavior most people will not do the second step.

Opinions?

**Comment by nmco** [comment]
@shadab-geo let's follow the usual workflow:

1. Clarify the context of the task, make sure you have everything needed to move on.
2. Provide a plan and estimate to handle the reported issue, report on the issue.
3. Wait for the green light from the PM before moving on with the implementation.

**Comment by shadab-geo** [comment]
Analysis: The details are saved only when the user clicks `save` on the edit layer page. It looks that we need to explicitly save the `FeatureTypeInfo` in https://github.com/shadab-geo/geoserver/blob/9e40cbbccb9626b8d08516c8eacaf5a8f168189b/src/web/core/src/main/java/org/geoserver/web/data/layer/SQLViewEditPage.java#L45 method to save it in a single click when on edit SQL view page.

**Comment by aaime** [comment]
From @simboss comment: " I think we need to make it more clear for the end user that we need to save twice before having the behavior applied, because with the current behavior most people will not do the second step."

So we were talking about a UI improvement, not a change in functionality.

**Comment by nmco** [comment]
@shadab-geo can you review your plan with @dromagnoli taking into account @aaime feedback?

**Comment by dromagnoli** [comment]
I agree with @aaime . I think that both Simone and Andrea are referring to a UI improvement.
Something like a label, or a message or whatever, warning the user about the double save needed to have changes applied.

**Comment by simboss** [comment]
correct @dromagnoli otherwise people will forget to save a second time!

**Comment by dromagnoli** [comment]
@shadab-geo I think that we can add some Note/Warning label text on the GUI in one of the 3 TEXT places in the below screenshots saying something like:
"Once Saved, make sure to save the layer configuration too to get the SQLView changes applied"
or
"After hitting Save, make also sure to save the layer configuration to get the SQLView changes applied"
or anything better/clear.

@aaime
I don't think we have any popup message or dialog windows showing up once clicking on a button so I think that the notice message should be part of the page itself, what do you think?

![sqlview](https://user-images.githubusercontent.com/1278116/133085005-5a81bb65-6b99-4d70-bfcc-264376d44688.png)

**Comment by aaime** [comment]
First suggest would be, change that "save" button into a "Back" button, or a "back to layer" link.
If it does not look like a button at all, it's going to be less likely to confuse people.

About the message, yep, not sure... one can try to add a info feedback message right before returning to the layer page and see if that shows up. Or just put a static message below the link, that would be good too I think.

**Comment by shadab-geo** [comment]
JIRA: https://osgeo-org.atlassian.net/browse/GEOS-10232

**Comment by shadab-geo** [comment]
PR: https://github.com/geoserver/geoserver/pull/5283

**Comment by nmco** [comment]
I would suggest that we backport to 2.19.x.

**Comment by shadab-geo** [comment]
Backport PR: https://github.com/geoserver/geoserver/pull/5290

**Comment by shadab-geo** [comment]
backport 2.20.x: https://github.com/geoserver/geoserver/pull/5297

**Comment by dromagnoli** [comment]
All backports have been merged
