### ISSUE TITLE
Improve parameters extractor plugin logging and auditing capabilities

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#231]
Parameters extractor plug-in as been graduated to an official extension and its used by several clients in production, unfortunately to logging is not great. We should at least:
- At INFO level log the full HTTP request after it has been transformed.
- At TRACE level log which rules are applied or rejected.
- It should be possible to integrate it whit the monitor plug-in. 
- A message should be logged when the plug-in loads up, saying for example that all rules where successfully loaded up.

**Comment by nmco** [comment]
@taba90 let's spend 1hour MAX preparing a plan whit the requested enhancements above, then let's discuss what to do next.

**Comment by taba90** [comment]
@nmco 

1. Looks like there are already the logs that you are expecting:
      - [Here] (https://github.com/geoserver/geoserver/blob/8fd0b0884570f9536c591d88d78354393058e263/src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/Rule.java#L60) logs are applied to rules that are deactiveted or not applied; the Log level is DEBUG if needed we can change it to TRACE.
     - [Here](https://github.com/geoserver/geoserver/blob/8fd0b0884570f9536c591d88d78354393058e263/src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/Filter.java#L91) both the original url and the trasformed one are logged.

2. Regarding the monitoring looks that both the original and the trasformed urls are logged.
3. regarding the succesfull rules loading up I guess that we could add log [here ](https://github.com/geoserver/geoserver/blob/8fd0b0884570f9536c591d88d78354393058e263/src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/Filter.java#L74) where the Filter init the existing rules. **Estimate for this is < 1 hour**.

**Comment by nmco** [comment]
@taba90 documentation of the module should be updated whit this information:
- How to check the log to understand that the module was properly loaded up.
- How to check at INFO level the URL was transformed, both on log and auditing.
- How at DEBUG level understand which rules where tried out and the outcome of each one.
- Basically when debugging a problem whit parameters extractor we should be able to understand the full picture. 

Please review your plan taking this into account.

How is the test coverage of the module?

**Comment by nmco** [comment]
Another aspect, when the rules are changes or updated, that should be clear on the log.

**Comment by taba90** [comment]
@nmco attached is the logged request from the monitoring plug-in.
In conclusion:
- To log when a rule is updated or saved or deleted logs will be added to the [RuleDao](https://github.com/geoserver/geoserver/blob/8fd0b0884570f9536c591d88d78354393058e263/src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/RulesDao.java).
- Info log will be added [here ](https://github.com/geoserver/geoserver/blob/8fd0b0884570f9536c591d88d78354393058e263/src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/Filter.java#L74)to make it clear that the module was properly loaded up.
- Documentation will be updated giving hints about how to check geoserver and audit logs the operations performed by the plugin.
Estimate is **3 hours**.

**Comment by nmco** [comment]
Could you be a bit more explicit, it's not clear to me what I should look like in the audit logging, looks like only the query string is logged, there is no hint that parameters extractor did anything no?

What we need here is pretty practical; **We are investigating an issue in a production environment that we don't' have access too, and we need to understand what parameters extractor is doing just by looking at the logs. INFO level should give a basic understanding and the DEBUG level and detailed understanding.**

In more detail, at:
* INFO level, we need to be able to understand that:
  * Parameters extractor plug-in was correctly loaded.
  * Parameters extractor plug-in rules were successfully loaded.
  * Parameter rules where updated a re-loaded.
  * When rules are (re-)loaded they should be listed, remember we don't have access to the data directory.
  * When a request URL hits GeoServer we should see in the log the original URL and the produced URL, I think this log already exists.
  * When an URL is not translated we should still see some parameters extractor logging, the goal is to make clear that parameters extractor is present and tried to do something.
* DEBUG level, we should be able to understand that:
  * When a request is evaluated we should be able to check the intermediary result of each rule evaluation. 

For the audit | monitoring it should be clear that parameters extractor was present and did something, I would say that adding something like:
```
(...)
<ParametersExtractorTransformed>TRUE | FALSE</ParametersExtractorTransformed>
<OriginalPath>/tiger/wms/A41</OriginalPath>
<OriginalQueryString>request=GetMap&amp;srs=EPSG:4326&amp;service=WMS&amp;bbox=-74.02722,40.684221,-73.907005,40.878178&amp;layers=tiger:tiger_roads&amp;width=476&amp;format=application/openlayers&amp;styles=&amp;version=1.1.0&amp;height=768</OriginalQueryString>
(...)

What about the test coverage? Can you measure it whit InteliJ?

Please review your estimate taking into account the points above, thank you.

**Comment by taba90** [comment]
@nmco 
The audit logger is logging both the request before rules being applied and after: as it is possible to see the first url has the right side of the filter provided in the url path, while the second one has it in the query parameter. Thinking in practical term seems to me that this is a clear signal that the params extractor applied a rule. Anyway a plan and an estimate for add additional fields to the audit logger is provided below.

- test coverage is 95% of classes 84% of methods and 76% of lines of code. All the major functionalities are covered. We might think to add some test for some utility and dao method that are not tested.
![CoverageReport](https://user-images.githubusercontent.com/46672505/113178930-5b7e2f00-924f-11eb-8b12-ec2e93eea8e3.PNG)
- The INFO and DEBUG level logs that you are asking are already provided as stated above (there are code pointers).
- To log when a rule is updated or saved or deleted logs will be added to the [RuleDao](https://github.com/geoserver/geoserver/blob/8fd0b0884570f9536c591d88d78354393058e263/src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/RulesDao.java).
- Info log will be added [here ](https://github.com/geoserver/geoserver/blob/8fd0b0884570f9536c591d88d78354393058e263/src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/Filter.java#L74)to make it clear when the module is loaded and rules are reloaded (inside the init method).
- Documentation will be updated giving hints about how to check geoserver and audit logs the operations performed by the plugin.
- Regarding the integration with monitor plug-in: to add a new value it is needed to add a dependency to the monitor plug-in in the params extractor module, since the freemarker template context doesn't have any other way to access a new attribute that is specific to the params extractor semantic. It would be necessary to create a [RequestData ](https://github.com/geoserver/geoserver/blob/0df54fcc76e23ced75dc9ffbebedb7ae5d7bb797/src/extension/monitor/core/src/main/java/org/geoserver/monitor/RequestData.java#L23) wrapper or to extend it to add the new field. [Then in the Params extractor plug-in
](https://github.com/geoserver/geoserver/blob/8fd0b0884570f9536c591d88d78354393058e263/src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/Filter.java#L24) add a dependency to the [Monitor class](https://github.com/geoserver/geoserver/blob/de184b2f9ed9a844b5291dd163e772132a07689b/src/extension/monitor/core/src/main/java/org/geoserver/monitor/Monitor.java) to create a RequestData object update it with the needed field and save it to the MonitorDao and the Audit logs estimated time for this is **6-7 hours.**

Estimate is **3 hours** without Monitor integration and **9-10 hours** with it

**Comment by nmco** [comment]
Please provide concrete examples of all the logs messages we will see (include the ones that already exists) [HERE](https://docs.google.com/document/d/1CIiKmS9bqHYmWDCb45omNd2ScLxDUKX2pI5LPmwjRyk/edit?usp=sharing). This is a quick thing to do and will make sure we are all on the same page.

**Comment by nmco** [comment]
TDMS is having troubles again @taba90, I have sent an invite for tomorrow so we can look at the TDMS report together.

**Comment by taba90** [comment]
@nmco the document at the url has been updated.
I've checked the client logs here a first report:
- from those logs seems that the params extractor is not active: the info log should log the url before and after rules are applied doesn't appear. A log like this one should be present when rules are applied  to incoming url:
``07 apr 12:17:41 INFO [org.geoserver.params.extractor] - Request '/geoserver/tiger/wms/A41?request=GetMap&srs=EPSG%3A4326&service=WMS&bbox=-74.02722%2C40.684221%2C-73.907005%2C40.878178&layers=tiger%3Atiger_roads&width=476&format=application%2Fopenlayers&styles=&version=1.1.0&height=768'  
transformed to 
'/geoserver/tiger/wms?request=GetMap&srs=EPSG%3A4326&service=WMS&bbox=-74.02722%2C40.684221%2C-73.907005%2C40.878178&layers=tiger%3Atiger_roads&width=476&format=application%2Fopenlayers&styles=&cql_filter=CFCC%3D%27A41%27&version=1.1.0&height=768'.``

- However logs are the old ones we might need new ones.
- More logs are activated with a DEBUG level, thus we would need the logs produced with a profile equal to either **geoserver_developer_logging** or **verbose_logging**.

**Comment by nmco** [comment]
Some improvements implemented [HERE](https://osgeo-org.atlassian.net/browse/GEOS-10019).
