### ISSUE TITLE
Plan to implement the XML feature templating support

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#245]
Can you detail on this issue @taba90 the plan for the implementation of the XML templating support? Make sure you include:
- Re-factoring of the existing builders architecture.
- Implementation of the XML templating.
- Implementation of the GML and HTML templating.

Don't be afraid of provided technical details.

**Comment by taba90** [comment]
@nmco attached are two mocks of the gml and xhtml templates.

The implementation plan is the following:

- Currently builders (the template bricks) are created trough a [BuilderFactory](https://github.com/geoserver/geoserver/blob/a717c858fd786e81b024e87c199b40054b1beda1/src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/BuilderFactory.java#L26) that is pretty basic and dummy. The plan is to refact that part trough Abstract Factory: a new class will receive an input stream of the template resource and the output format request and will return the correct factory to be used eg. XML or JsonFactory. The current JsonTemplateReader will be then renamed to make it clear that it is a factory. A new `XMLTemplateFactory` will be created and will use [StAX api](https://docs.oracle.com/javase/tutorial/jaxp/stax/api.html) to parse the the gml and xhtml templates.
- New builders class will need to be created in order to handle the attributes in a gml element. Namely we need ad hoc subclass for the [Dynamic ](https://github.com/geoserver/geoserver/blob/a717c858fd786e81b024e87c199b40054b1beda1/src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicValueBuilder.java#L23) and [Static ](https://github.com/geoserver/geoserver/blob/a717c858fd786e81b024e87c199b40054b1beda1/src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/StaticBuilder.java#L23) builders, named `XMLAttributeDynamicBuilder` and `XMLAttributeStaticBuilder`, and will support the encoding of xml element attributes.
- A [new writer](https://github.com/geoserver/geoserver/blob/ee4bd95ffe8dd862ac6375e332fc5fb6c6957582/src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/TemplateOutputWriter.java#L12) implementation will be created using [StAX api](https://docs.oracle.com/javase/tutorial/jaxp/stax/api.html) to write both gml and html output format.
- New Response implementation will be needed to handle the HTML and GML templating and will need to wrap the existing ones for GML and HTML both WFS and OGCAPI flavoures.
- Additional notes on templates: we need a way to tell when a template piece is referring to a ComplexType unbounded or with maxOccurs=1 to decide if build an Iterating builder or a Complex builder. This can be in theory done automatically as long as we have a source (evaluate it against the featureType and detect if maxValue is unbounded) but it is not mandatory to have it in an iterating builder. I was thinking to add an attribute to mark arrays in xml to make life easier you will find it in the mocks.

[templates-mocks.zip](https://github.com/geosolutions-it/geoserver/files/6249095/templates-mocks.zip)

**Comment by nmco** [comment]
Two notes:
- We may need to rely on the SAX parser because of the namespaces not being always defined.
- Namespaces will need to be included (there is a dedicated issue for this).
- An example of an XML template is available [HERE](https://docs.google.com/document/d/1M8pWlhaL3I5sVtweIJnN622-ja5AOajWryDQFudAR4U/edit).
