### ISSUE TITLE
Geoserver cannot retrieve the image set in an ExternalGraphic SLD element

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geoserver#280]
Something goes wrong with **Geoserver** with [this image](https://pngimg.com/uploads/mario/mario_PNG53.png), which can be reached from the Geoserver machine (tested with `wget`. If I use it inside the following correct style, I get the WARNING reported below, and the final marker is a **grey square**.

**Style**
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<StyledLayerDescriptor version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NamedLayer>
    <Name>A dark orange polygon style</Name>
    <UserStyle>
      <Name>A dark orange polygon style</Name>
      <Title>A dark orange polygon style</Title>
      <FeatureTypeStyle>
        <Rule>
          <Name/>
          <PointSymbolizer>
            <Graphic>
              <ExternalGraphic>
                <OnlineResource xlink:type="simple" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://pngimg.com/uploads/mario/mario_PNG53.png"/>
                <Format>image/png</Format>
              </ExternalGraphic>
              <Opacity>1</Opacity>
              <Size>32</Size>
            </Graphic>
          </PointSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
```

**Geoserver warning**
`WARN [renderer.style] [http-nio-8080-exec-5] - Unable to read image at https://pngimg.com/uploads/mario/mario_PNG53.png : Can't create an ImageInputStream!`

**Comment by aaime** [comment]
Why do you want to put Mario on a map though??

![image](https://user-images.githubusercontent.com/325433/116682153-2a0f9500-a9ae-11eb-8c48-ecbe0e7cb04e.png)

**Comment by simboss** [comment]
clients can be demanding at times...

**Comment by aaime** [comment]
It's happening because some web sites have started blocking Java as the user agent, returning back a 403.

See here, with wget, just changing the user agent.
First request, not setting the user agen, saved succesfullyt:

```
> wget https://pngimg.com/uploads/mario/mario_PNG53.png
--2021-04-30 12:36:01--  https://pngimg.com/uploads/mario/mario_PNG53.png
Risoluzione di pngimg.com (pngimg.com)... 104.26.4.108, 104.26.5.108, 172.67.75.130, ...
Connessione a pngimg.com (pngimg.com)|104.26.4.108|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: 2255969 (2,2M) [image/png]
Salvataggio in: "mario_PNG53.png"

mario_PNG53.png                                             100%[=========================================================================================================================================>]   2,15M  5,56MB/s    in 0,4s    

2021-04-30 12:36:02 (5,56 MB/s) - "mario_PNG53.png" salvato [2255969/2255969]
```

And then one setting the same user agent the java URL class ends up using under covers:

```
> wget -U "Java/1.8.0_282"  https://pngimg.com/uploads/mario/mario_PNG53.png
--2021-04-30 12:36:56--  https://pngimg.com/uploads/mario/mario_PNG53.png
Risoluzione di pngimg.com (pngimg.com)... 172.67.75.130, 104.26.5.108, 104.26.4.108, ...
Connessione a pngimg.com (pngimg.com)|172.67.75.130|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 403 Forbidden
2021-04-30 12:36:56 ERRORE 403: Forbidden.
```

Boom, 403.
Looks like Java is used a lot to [write bots and crawlers](https://serverfault.com/questions/570166/block-bots-by-their-java-referrer-or-user-agent-string), and it [getting blocked](https://coreysalzano.com/how-to/block-java-user-agents/) as a consequence.

Now, thankfully the user agent can be configured as a system variable if you want to, e.g:

``
-Dhttp.agent=GeoServer
``

Allows me to get this map:

![image](https://user-images.githubusercontent.com/325433/116685282-5e855000-a9b2-11eb-84fe-30361de7a778.png)


"Marios.... Marios eveywhere!!!"

If we want to go for a code change instead, we can change these bits, and write code that explicitly handles HTTP connections and set a user agent of our choice:

https://github.com/geosolutions-it/imageio-ext/blob/master/library/streams/src/main/java/it/geosolutions/imageio/stream/input/spi/URLImageInputStreamSpi.java#L94

**Comment by giohappy** [comment]
> Why do you want to put Mario on a map though??

@aaime because I wanted to see the map tha you've pasted above!

I'll let @simboss decide on this. It's not a blocker for the client. This thing happened to me while testing other related problems (client side).

**Comment by simboss** [comment]
I don't think we need to do anything, we have a way to change the user agent which is good enough for me.

**Comment by giohappy** [comment]
@simboss ok, I didn't notice.
