### ISSUE TITLE
Investigate the situation reported by Sylvain

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#301]
Information available on mail whit subject ``App-schema bugfix files`` form the 29th of June.

**Comment by taba90** [comment]
- The issue is caused by primary key constraints in joined table.

[This piece of code](https://github.com/geotools/geotools/blob/ab69b3c8dee0b32058c33a93cf098a41592e1dc1/modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java#L1334) is reading the primary key in the select. 

- this will cause the value retrivial mechanism in the JDBCFeatureReader to use twice a value if it is a primary key. The needed fix is to check if the column has already been encoded in the primary key loop and the skip it eventually.

- The issue is part of, but not completely overlaps with the composite primary key - foreign key issue. 
- Test data used for the previous bug fix (boreholeview) did not have a primary key in the joined table indeed, neither the postgis app-schema integration test data.

Estimate for the fix is **2-3 hours**

**Comment by taba90** [comment]
gt pr has been made as well as gs test coverage.
Details in this jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6937
I've asked @fernandor777 to review it.

**Comment by nmco** [comment]
@Sylvain is on holiday this week, and @fernandor777 is super busy with a deadline, let's review this Friday or Monday @fernandor777.
