### ISSUE TITLE
Integrate features templating with WMS GetFeatureInfo operation

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#302]
The following project code should be use don the time-sheet, I keep the BRGM label so we keep track of this:
EMSA
C105-2021-EMSA-OGC-COD-1.0

The estimate for implementing this integration is one day.

**Comment by taba90** [comment]
@nmco 

- To implement the functionality implementation of the [GetFeatureInfo](https://github.com/geoserver/geoserver/blob/6e9e25c0c7cdda9ada9f33f8255130d3afc76801/src/wms/src/main/java/org/geoserver/wms/featureinfo/GetFeatureInfoOutputFormat.java#L50) base class are need for each output format that the features-templating plug-in might return.
- Internally those implementations can then call the the correspondly GetFeature class write method.
- JSON-LD those not currently has any strategy for multiple featuretype request with respect to the @context. Since  for wms we have LayerGroup this is likely to be a common use case. One strategy could be to merge all the context found in the various templates.
- Other output format should work just fine for LayerGroup but this need to be tested.
- At least **1.5** for feature info response implementation, json-ld @context merging and proper testing is needed.

**Comment by taba90** [comment]
everything merged and backported to 2.19.x
