### ISSUE TITLE
Issue in GeoServer WPS when exporting a layer with a spatial filter

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geoserver#324]
This is a placeholder for [this](https://github.com/GeoNode/geonode/issues/8460) issue in GeoNode.

**Comment by giohappy** [comment]
@simboss let me know who can work on this. It would be great if this could be solved before the 4.0 Alpha release and 3.3.1.

**Comment by simboss** [comment]
@giohappy this is now on @dromagnoli plate.

He shall start working on this soon...

**Comment by dromagnoli** [comment]
Hi, I have started the investigation. For some reason the filter is being parsed as
[ the_geom intersects POLYGON EMPTY ].
I'm looking for the piece of code which converts the input filter like that.
For some reason, IntelliJ is not stepping into the relevant breakpoints (that's a mistery, I have shown my debugging session to @aaime which confirms the mistery :D).
So I'm temporarly installing eclipse to debug that part of code.

**Comment by dromagnoli** [comment]
Hi @giohappy.
After some investigations I think that I have found the problem.

The filter being declared is 1.1 whilst the GML polygon definition used is GML v2 instead of GML v3 required by OGC Filter 1.1.

So, using gml:exterior instead of gml:outerBoundaryIs 
and gml:posList instead of gml:coordinates should do the trick.

(I did a test with some local data and after changing the polygon syntax is worked for me).

This is the polygon definition I have used with the States vector data from the training:
<gml:Polygon srsName="EPSG:3857"><gml:exterior><gml:LinearRing><gml:posList>-11662456.027639 5009377.085697 -11662456.027639 4050551.002887 -9236039.001754 4050551.002887 -9236039.001754 5009377.085697 -11662456.027639 5009377.085697</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon>


Whilst your polygon definition was:
<gml:Polygon srsName="EPSG:3857"><gml:outerBoundaryIs><gml:LinearRing><gml:coordinates>90319.02643363085,3414964.3591960706 90319.02643363085,3991448.246372885 687801.5984746646,3991448.246372885 687801.5984746646,3414964.3591960706 90319.02643363085,3414964.3591960706</gml:coordinates></gml:LinearRing></gml:outerBoundaryIs></gml:Polygon>

Where you can see it's using a GML 1.0/2.0 syntax for the polygon.

**Comment by giohappy** [comment]
Thanks @dromagnoli I will report this to the MapStore team to confirm the behaviour.

**Comment by simboss** [comment]
Closing this since it is not GeoServer related.
